4und-Cloud/TablePick-BackEnd

- src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #7
- 테스트를 위한 코드를 원래 코드로 수정했습니다.
- 주의사항
Closes #7
> TP-15 코드 수정

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
- src/main/java/com/goorm/tablepick/domain/member/exception/MemberErrorCode.java
- src/main/java/com/goorm/tablepick/domain/member/exception/MemberException.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
로그인 직후 사용자 정보 조회 API
- #10 
- 로그인 직후 마이페이지로 전달할 사용자 정보 조회 API
- 주의사항
Closes #10
> TP-41 사용자 정보 조회 API

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- #12 
- 사용자 정보 수정
- 주의사항
Closes #12
> TP-43 사용자 정보 수정 API

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/reservation/dto/response/ReservationResponseDto.java
- src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
- #13 
-사용자 예약 목록 조회 api
- 주의사항
Closes #13
> TP-40 내 예약 조회 API

- src/main/java/com/goorm/tablepick/domain/board/dto/MyBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
내 게시글 목록 조회 API
#14 
- 이슈번호
- 사용자 마이페이지에서 내 게시글 조회하는 api
- 주의사항
Closes #14
> TP-39 내 게시글 목록 조회 API

- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- src/main/java/com/goorm/tablepick/global/config/SwaggerConfig.java
- src/main/resources/application.yml
- #20 
- swagger jwt 설정 추가
- 주의사항
Closes #20
> TP-46 swagger 설정 추가

- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/dto/GoogleInfo.java
- src/main/java/com/goorm/tablepick/domain/member/dto/KakaoInfo.java
- src/main/java/com/goorm/tablepick/domain/member/dto/OAuthInfo.java
- src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
- src/main/java/com/goorm/tablepick/domain/member/repository/RefreshTokenRepository.java
- src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
- src/main/java/com/goorm/tablepick/global/jwt/JwtTokenFilter.java
- src/main/java/com/goorm/tablepick/global/jwt/JwtTokenService.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #23 
- 필드로 바꿈
- 주의사항
Closes #23
> Tp-58 member

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/entity/BoardImage.java
- [TP-61]
- 로그인 인증 객체 부분 수정
- BoardImage 부분에서 필드 추가
- url도 필요할 수 있어서 남겨 놓음.
-
- 주의사항
Closes #12
[TP-61]: https://partsmanagement2.atlassian.net/browse/TP-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TP-61] 게시물 코드 리팩토링 

- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantCategorySearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantKeywordSearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/MenuResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/PagedRestaurantResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantSearchResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/exception/RestaurantErrorCode.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/MenuRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantCategoryRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #28 
- 식당 검색 API
- 주의사항
Closes #28
> Tp-44 search

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardCategorySearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardKeywordSearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardSearchResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/PagedBoardsResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantCategorySearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantKeywordSearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #32 
- 게시물 카테고리로 필터링하는 작업했습니다.
- 주의사항
Closes #32
> Tp 63 search

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- #21 
- 로그아웃 API
- 주의사항
Closes #21
> TP-47 로그아웃 API

- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- #33 
- conflict 해결
- 주의사항
Closes #33
> [TP-62] 게시물 최신순(시간순) 정렬 리팩토링

- src/main/java/com/goorm/tablepick/TablePickBackEndApplication.java
- src/main/java/com/goorm/tablepick/domain/reservation/scheduler/ReservationSlotScheduler.java
- 이슈번호 #36 
- 예약 슬롯 자동 생성 스케줄러
- 주의사항
Closes #36
> [TP-67] reservation slot scheduler

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberAddtionalInfoRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/domain/member/repository/MemberTagRepository.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- src/main/java/com/goorm/tablepick/global/config/WebConfig.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #43 
- 로그인 API 수정
- 주의사항
Closes #43
> Tp 77 member

- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/PagedRestaurantResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #45 
- 식당 목록 페이지에서 리뷰순으로 식당을 보여지도록 작업했습니다.
- 주의사항
Closes #45
> Tp 78 restaurant

- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- src/main/java/com/goorm/tablepick/global/config/WebConfig.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #47 
- webconfig 수정
- 주의사항
Closes #47
> TP-79 cors 에러 코드 수정

- src/main/java/com/goorm/tablepick/domain/reservation/controller/ReservationController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- 이슈번호 #42 
- 예약 순으로 전체 식당 리스트 조회
- 주의사항
Closes #42
> Tp 74 restaurant

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #52 
- 작업 내용
- 주의사항
Closes #52
> TP-81 로그인 로직 수정

- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardDetailResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardSearchResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberAddtionalInfoRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
- src/main/java/com/goorm/tablepick/domain/reservation/dto/response/ReservationResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/MenuResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantResponseDto.java
- #54 
- 프론트 로그인 연동중 데이터 안넘어가는 에러 해결
- 주의사항
Closes #54
> TP-81 DTO @Getter @Setter 추가

- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/data/RestaurantDataImporter.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantDetailResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantImageResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantOperatingHourResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantTagResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Menu.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/RestaurantImage.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/RestaurantTag.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- 이슈번호 #50 
- 식당 상세 정보 조회
- 주의사항
Closes #50
> [TP-76] restaurant detail

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
- #58 
- 작업 내용
- 주의사항
Closes #58
> TP-85 검색 유효성 코드 수정

- src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
- src/main/java/com/goorm/tablepick/domain/notification/dto/request/FCMTokenRequest.java
오타 수정
- #63
- 오타 수정
- 주의사항
Closes #63
> [TP-92] 코드 디버깅

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
[TP-94] 게시글 목록 페이지 6개 조회 API #66
게시글 목록 조회시에 게시글을 6개씩 보여주는 api 기능입니다.
- 주의사항
Closes #12
[TP-94]: https://partsmanagement2.atlassian.net/browse/TP-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TP-94] 게시글 목록 페이지 6개 조회 API #66

- src/main/java/com/goorm/tablepick/domain/notification/constant/NotificationTypes.java
- src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
- src/main/java/com/goorm/tablepick/domain/notification/entity/Notification.java
- src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationLog.java
- src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationTypes.java
- src/main/java/com/goorm/tablepick/domain/notification/repository/NotificationTypesRepository.java
- src/main/java/com/goorm/tablepick/domain/notification/service/FCMTokenService.java
- src/main/java/com/goorm/tablepick/domain/notification/service/NotificationService.java
- src/main/resources/static/alarmtest.html
- #73 
- html 수정 및 이름 변경, 알림 관련 이름과 타입 불일치 수정, 빌더 패턴으로 수정
- 주의사항
Closes #12
> TP- 88 fcm 알림 테스트 html 디버깅, 이름 변경 및 타입 불일치, 빌더 패턴으로 수정

- src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationLog.java
- src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
- src/main/java/com/goorm/tablepick/domain/tag/controller/TagController.java
- src/main/java/com/goorm/tablepick/domain/tag/dto/TagResponseDto.java
- src/main/java/com/goorm/tablepick/domain/tag/repository/TagRepository.java
- src/main/java/com/goorm/tablepick/domain/tag/service/TagService.java
- src/main/java/com/goorm/tablepick/domain/tag/service/TagServiceImpl.java
- src/main/resources/application.yml
- #79 
- 태그 조회 API
- 주의사항
Closes #79
> TP-104 태그 조회 API

- src/main/java/com/goorm/tablepick/domain/restaurant/controller/CategoryController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/CategoryResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #80 
- 카테고리 조회 API
- 주의사항
Closes #80
> TP-106 카테고리 조회 API

- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
- #84 
- 작업 내용
- 주의사항
Closes #84
> TP-108 jwt 코드

- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #86 
- 작업 내용
- 주의사항
Closes #86
> TP-109 식당 랜딩 페이지 정보 추가

- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- #89 
- 인증객체 안넘어가는 문제 해결
- 주의사항
Closes #89
> TP-111 jwtTokenFilter 에러 해결

- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- #91  
- 시큐리티 비인증 경로 추가
- 주의사항
Closes #91
> [TP-114] 시큐리티 로그인 전 경로 추가

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardRequestDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- [TP-110]
- 게시글 목록 조회 화면(메인: 4개씨가, 더보기 : 6개씩) 식당명, 식당주소, 태그, 프로필 이미지, 사용자 닉네임을 추가하였습니다.
- 잘 나오는지 확인 부탁드립니다.
- 주의사항
Closes #12
[TP-110]: https://partsmanagement2.atlassian.net/browse/TP-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TP-110-board-list-api-update

- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
- #97 
- 작업 내용
- 주의사항
Closes #97
> TP-117 식당 이미지 추가

- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- #104 
- 작업 내용
- 주의사항
Closes #104
> [TP-120] 로그아웃 CORS 에러 해결

- src/main/java/com/goorm/tablepick/TablePickBackEndApplication.java
- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardDetailResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/PagedBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- [TP-112]
- 게시글 6개씩 보는 부분에 불러오는 항목 추가
- 게시글 상세보기 페이지 api 구현
- 주의사항
Closes #12
[TP-112]: https://partsmanagement2.atlassian.net/browse/TP-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TP-112] 게시글 상세 페이지 API 수정 #94

- src/main/java/com/goorm/tablepick/domain/member/dto/MemberAddtionalInfoRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/domain/member/entity/MemberTag.java
- src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- #110 
- 작업 내용
- 주의사항
Closes #110
> TP-122 멤버 태그 에러 수정

- .gitignore
- src/main/resources/firebase-service-account.json
- src/main/resources/static/alarmtest.html
- src/main/resources/static/firebase-messaging-sw.js
- #106 
- FCM 관련 민감 정보 분리 및 파일화
- 소스트리, 깃크라켄 등으로 작업 완료 후 push 하실 때 fcm 관련 키가 있는 파일은 안 올리도록 조심하시기 바랍니다.
- 키 값 등이 적힌 firebaseConfig.ts는 .gitignore에 적어 놨으니 키 등이 적힌 파일만 안 올라가도록 주의 바랍니다.
- ex) alartest.html, firebase-messaging-sw.js, firebase-service-account.json 등
Closes #106
> [TP-121] FCM 민감 정보 관리 파일

- src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationRepository.java
- #113 
- 작업 내용
- 주의사항
Closes #113
> TP-123 내 예약 조회 CANCELLED 제외

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardCreateResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/request/BoardRequestDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardSearchResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/entity/Board.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- src/main/java/com/goorm/tablepick/global/config/WebConfig.java
[TP-113]
원래는 TP-113에서 게시글 생성 API 작업을 하려고 했지만,
일정상 먼저 조회 관련 작업을 선행하였습니다.
- 엔티티 관계 수정 및 매핑 완료
- 게시글 메인 화면 조회 API
- 게시글 리스트 조회 API
- 게시글 상세 조회 API
게시글 생성 기능은 이어서 별도 커밋 또는 PR에서 처리할 예정입니다.
- 주의사항
Closes #12
[TP-113]: https://partsmanagement2.atlassian.net/browse/TP-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [TP-113] 게시글 조회 API 구현 (생성은 추후 진행)

- src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
- src/main/java/com/goorm/tablepick/domain/notification/service/FCMTokenService.java
- src/main/java/com/goorm/tablepick/domain/notification/service/NotificationService.java
- #115 
- 로그아웃 하면 delete 방식이 아닌 patch 방식으로 fcm토큰을 null로 바꿈
- 주의사항
Closes #115
> [TP-124] 로그아웃 하면 fcm토큰이 null로 변경, DELETE에서 PATCH로 변경

- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #118 
-리프레시 토큰 수정
- 주의사항
Closes #118
> TP-127 리프레시 토큰 수정

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardCreateResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardImageRepository.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardTagRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- src/main/java/com/goorm/tablepick/global/security/CustomUserDetails.java
- #117 
- 게시물 작성(생성) 작업
- 주의사항
Closes #117
> [TP-125] 게시글 생성 페이지 API

- src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
order by 추가
- #128 
- 해당하는 태그 수가 많은 순서대로 정렬
- 주의사항
Closes #128
> TP-133 검색 API

- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- 이슈번호
- 작업 내용
- 주의사항
Closes #12
> TP-141 리프레시 토큰 재발급 로직 수정

- src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
- src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/domain/member/exception/MemberErrorCode.java
- src/main/java/com/goorm/tablepick/domain/member/exception/MemberException.java
- src/main/java/com/goorm/tablepick/domain/member/service/CustomOAuth2UserService.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- #133 
- 작업 내용
- 주의사항
Closes #133
> TP-137 코드 리팩토링

- src/main/java/com/goorm/tablepick/domain/member/dto/MemberUpdateRequestDto.java
- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/domain/member/entity/MemberTag.java
- src/main/java/com/goorm/tablepick/domain/member/exception/MemberErrorCode.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- #143 
- 멤버 업데이트 수정
- 주의사항
Closes #143
> TP-144 멤버 업데이트 수정

- src/main/java/com/goorm/tablepick/domain/notification/entity/NotificationTypes.java
- #147 
- NotificationTypes 코드 수정
- 주의사항
Closes #147
> [TP-147] NotificationTypes 에러 디버깅 완료

- src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- #151 
- 작업 내용
- 주의사항
Closes #151
> TP-150 멤버 createAt 추가

- src/main/java/com/goorm/tablepick/global/config/NotificationTypesInitializer.java
- #150 
- 알림의 타이틀과 바디 수정
- 주의사항
Closes #150
> [TP-148] 알림 타이틀, 바디 수정

- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #159 
- 검색 태그많은 순 정렬
- 주의사항
Closes #159
> TP-146 검색 API 태그 많은 순 정렬

- src/main/java/com/goorm/tablepick/domain/notification/repository/NotificationLogRepository.java
- src/main/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImpl.java
- #158 
- jpa, serviceimpl에서 관련 코드 수정
- 주의사항
Closes #158
> [TP-155] 회원 알림 목록 조회할 때 null 나오는 것들 디버깅

- src/main/java/com/goorm/tablepick/domain/notification/dto/response/NotificationResponse.java
- src/main/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImpl.java
- #163 
- 프론트에 식당 이름도 넘겨줌
- 주의사항
Closes #163
> [TP-155] 회원 알림 목록 안보이던 현상 디버깅

- src/main/java/com/goorm/tablepick/domain/member/dto/MemberResponseDto.java
- #169 
- 사용자태그 추가
- 주의사항
Closes #169
> [TP-158] 사용자 정보 추가

- src/main/java/com/goorm/tablepick/global/config/NotificationTypesInitializer.java
- #167 
- 알림 타이틀 수정
- 주의사항
Closes #157
> [TP-157] 알림 타이틀 수정

- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/RestaurantListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- #172 
- 작업 내용
- 주의사항
Closes #172
> [TP-159] 식당 검색 목록 조회 리팩토링

- src/main/java/com/goorm/tablepick/domain/board/dto/response/MyBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/entity/BoardTag.java
- src/main/java/com/goorm/tablepick/domain/member/service/MemberServiceImpl.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- #177 
- 작업 내용
- 주의사항
Closes #177
> [TP-161] 내 게시글 목록 데이터 수정

- src/main/java/com/goorm/tablepick/domain/board/entity/Board.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- #182 
- ERD 변경에 따른 Board 코드 수정
- 주의사항
Closes #182
> TP-163 refactor: Update Board entity to reflect ERD changes

- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/dto/response/PagedBoardListResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- #190 
- ERD 변경에 따른 Board 코드 수정
- 주의사항
Closes #190
> TP-163 refactor: Update Board entity and repository for ERD changes

- src/main/java/com/goorm/tablepick/domain/member/controller/MemberController.java
- src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #194 
- 작업 내용
- 주의사항
Closes #194
> [TP-145] 리프레시 토큰 수정

- src/main/java/com/goorm/tablepick/domain/member/entity/RefreshToken.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- #199 
- 작업 내용
- 주의사항
Closes #199
> [TP-170] 로그인 에러 수정

- src/main/java/com/goorm/tablepick/domain/board/dto/response/BoardDetailResponseDto.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- #202 
- Board 상세 조회 response 수정
- 
- 주의사항
Closes #202
> TP-171 refactor: board-detail-response-structure

- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #205 
- 작업 내용
- 주의사항
Closes #205
> [TP-173] 리프레시 토큰 재로그인시 업데이트

- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/repository/BoardRepository.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- #224 
- 로그인 시 게시글 추천 AI 서버 연결
- AI 서버가 켜져 있지 않으면 로그인 시에 게시글 목록을 불러올 수 없고 서버에 오류 로그가 뜰 수 있습니다.
- 서버 주소는 나중에 board-image-path 수정할 때 같이 yaml에서 작업할 계획입니다.
Closes #12
> feat: connect AI server for board recommendation after login

- k6-scripts/reservation-test.js
- src/main/java/com/goorm/tablepick/domain/reservation/entity/ReservationSlot.java
- src/main/java/com/goorm/tablepick/domain/reservation/service/ReservationExternalUpdateService.java
- src/main/java/com/goorm/tablepick/domain/reservation/service/ReservationImpl.java
- 이슈번호 #249 
- 작업 내용
- 주의사항
Closes #12
> Tp 202 load test

- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplTest.java
- #232 
- 메시지에 로고 포함된 알림 전송 테스트
- 주의사항
Closes #232
> [TP-185] 로고 포함 알림 메시지 전송 테스트 성공

- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- #252 
- 작업 내용
- 주의사항
Closes #252
> [TP-205] session 만료시 토큰 만료 설정

- k6-scripts/reservation-test2.js
- src/main/java/com/goorm/tablepick/domain/reservation/controller/ReservationTestController.java
- src/main/java/com/goorm/tablepick/domain/reservation/facade/CreateReservationFacade.java
- src/main/java/com/goorm/tablepick/domain/reservation/facade/CreateReservationTestFacade.java
- src/main/java/com/goorm/tablepick/domain/reservation/repository/ReservationSlotRepository.java
- src/main/java/com/goorm/tablepick/domain/reservation/service/ReservationExternalUpdateService.java
> [TP-202] 비관적락 낙관적락 테스트 API 분리

- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplTest.java
- #233 
- 테스트 코드 리팩토링 및 테스트 코드 작성
- 주의사항
Closes #233
> [TP-186] fcm 토큰이 null이거나 비어있으면 전송하지 않고 에러 메시지 보내는지 테스트 성공

- build.gradle
- src/main/resources/application.yml
- src/test/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantCategoryRepositoryTest.java
- src/test/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryTest.java
- src/test/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceTest.java
- 이슈번호 #255 
- 작업 내용
- 주의사항
Closes #12
> [TP-203] 테스트 코드 임시 제외

- .github/workflows/deploy.yml
- 이슈번호 #255 
- 작업 내용
- 주의사항
Closes #12
> [TP-203] ecr 이름 수정

- src/main/java/com/goorm/tablepick/global/config/WebConfig.java
- src/main/java/com/goorm/tablepick/global/jwt/OAuth2AuthenticationSuccessHandler.java
- src/main/resources/application.yml
- #262 
- 환경 변수 관리
- env파일 받아서 각 환경에 맞게 변경해서 사용하시면 됩니다.
Closes #262
> [TP-210] 환경 변수 관리

- src/main/java/com/goorm/tablepick/global/jwt/JwtProvider.java
- 이슈번호 #255 
- 작업 내용
- 주의사항
Closes #12
> [TP-203] jwt 길이 변경

- src/main/java/com/goorm/tablepick/domain/notification/service/FCMServiceImpl.java
- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplTest.java
- src/test/resources/application.yml
- #275 
- 작업 내용
- 주의사항
Closes #275
> [TP-212] 알림 이미지 안 나오던 현상 디버깅

- src/main/java/com/goorm/tablepick/domain/notification/service/FCMServiceImpl.java
- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplTest.java
- #268 
- 작업 내용
- 주의사항
Closes #268
> [TP-211] 테스트코드 및 서비스 구현체 리팩토링

- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplIntegTest.java
- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplTest.java
- #258 
- 일반 알림 송수신 테스트 성공
- 이미지 알림 송수신 테스트 성공
- 주의사항
Closes #258
> [TP-207] FCM과 연동하여 알림, 이미지 포함 알림 송수신 테스트 성공

- .github/workflows/deploy.yml
- 이슈번호 #255 
- 작업 내용
- 주의사항
Closes #12
> [TP-203] 설정 파일 수정

- build.gradle
- src/main/java/com/goorm/tablepick/domain/notification/service/FCMServiceImpl.java
- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplIntegTest.java
- src/test/java/com/goorm/tablepick/domain/notification/service/FCMTokenServiceImplTest.java
- src/test/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryTest.java
- #234 
- 작업 내용
- 주의사항
Closes #234
> [TP-187] FCMTokenServiceImpl 테스트 코드 작성, 기타 오류 수정

- src/test/java/com/goorm/tablepick/domain/notification/service/FCMTokenServiceImplIntegTest.java
- #235 
- 작업 내용
- 주의사항
Closes #235
> [TP-188] FCMTokenServiceImpl 통합 테스트 성공

- src/test/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImplTest.java
- #236 
- 작업 내용
- 주의사항
Closes #236
> [TP-189] NotificationServiceImpl 테스트 성공

- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/request/RestaurantSearchRequestDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/dto/response/PagedRestaurantSearchResponseDto.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepository.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryCustom.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- #299 
- 검색 필터 추가, 정렬 추가
- 주의사항
Closes #299
> [TP-216] 검색 필터 추가

- src/main/java/com/goorm/tablepick/domain/member/entity/Member.java
- src/main/java/com/goorm/tablepick/domain/restaurant/entity/Restaurant.java
- src/test/java/com/goorm/tablepick/domain/notification/service/NotificationServiceImplIntegTest.java
- #237 
- 작업 내용
- 주의사항
Closes #237
> [TP-190] NotificationServiceImpl 통합 테스트 성공

- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplIntegTest.java
- src/test/java/com/goorm/tablepick/domain/notification/service/FCMTokenServiceImplTest.java
- src/test/java/com/goorm/tablepick/domain/notification/service/RegisterNotificationServiceImplIntegTest.java
- src/test/java/com/goorm/tablepick/domain/notification/service/RegisterNotificationServiceImplTest.java
- #239 
- 작업 내용
- 주의사항
Closes #239
> [TP-192] RegisterNotificationServiceImplTest 통합 테스트 성공

- src/test/java/com/goorm/tablepick/domain/notification/service/ReservationNotificationSchedulerImplTest.java
- #240 
- 작업 내용
- 주의사항
Closes #240
> [TP-193] ReservationNotificationSchedulerImpl 테스트 성공

- build.gradle
- src/main/java/com/goorm/tablepick/domain/board/controller/BoardController.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardService.java
- src/main/java/com/goorm/tablepick/domain/board/service/BoardServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/userevent/controller/UserEventController.java
- src/main/java/com/goorm/tablepick/domain/userevent/dto/UserClickEventDto.java
- src/main/java/com/goorm/tablepick/domain/userevent/service/UserEventService.java
- src/main/java/com/goorm/tablepick/domain/userevent/service/UserEventServiceImpl.java
- src/main/java/com/goorm/tablepick/global/config/KafkaProducerConfig.java
- src/main/java/com/goorm/tablepick/global/kafka/KafkaUserEventProducer.java
- src/main/resources/application.yml
- src/test/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceTest.java
- #304 
- 식당 및 게시글 CTR 관련 로그 전송 기능 구현
- docker에 kafka 환경 필요
Closes #304
> [TP-218] 식당 및 게시글 CTR 관련 로그 전송 기능 구현

- src/test/java/com/goorm/tablepick/domain/notification/service/ReservationNotificationSchedulerImplIntegTest.java
- #241 
- 작업 내용
- 주의사항
Closes #241
> [TP-194] ReservationNotificationSchedulerImpl 통합 테스트 성공

- .gitignore
- #310 
- 작업 내용
- 주의사항
Closes #310
> [TP-221] gitignore 추가

- build.gradle
- src/main/java/com/goorm/tablepick/global/config/SecurityConfig.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- src/main/resources/application.yml
- #312 
- 프로메테우스 & 그라파나 모니터링 환경 구축
- 도커에 프로메테우스 필요
Closes #312
> [TP-220] 프로메테우스 & 그라파나 모니터링 환경 구축

- src/test/java/com/goorm/tablepick/domain/notification/controller/NotificationControllerTest.java
- #242 
- 작업 내용
- 주의사항
Closes #242
> [TP-195] NotificationController 테스트 성공

- src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- src/test/java/com/goorm/tablepick/domain/notification/controller/NotificationControllerIntegTest.java
- #242 
- 필터에 테스트의 @ActiveProfiles("test")는 통과하도록 수정
- 주의사항
Closes #242
> [TP-195] NotificationController 통합 테스트 성공

- src/main/java/com/goorm/tablepick/domain/restaurant/controller/RestaurantController.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryCustom.java
- src/main/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryImpl.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantService.java
- src/main/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceImpl.java
- src/test/java/com/goorm/tablepick/domain/restaurant/repository/RestaurantRepositoryTest.java
- src/test/java/com/goorm/tablepick/domain/restaurant/service/RestaurantServiceTest.java
- #317 
- 작업 내용
- 주의사항
Closes #317
> [TP-223] 검색 페이지네이션

- src/test/java/com/goorm/tablepick/domain/notification/controller/NotificationScheduleControllerTest.java
- #243 
- 작업 내용
- 주의사항
Closes #243
> [TP-196] NotificationScheduleController 테스트 성공

- src/test/java/com/goorm/tablepick/domain/notification/service/FCMServiceImplIntegTest.java
- #325 
- 비동기, 순차 알림 발송 추가
- 주의사항
Closes #325
> [TP-229] FCM 알림 100개 발송 테스트 성공

- src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
- src/main/java/com/goorm/tablepick/domain/notification/dto/response/NotificationTestStatistics.java
- #327 
- 작업 내용
- 주의사항
Closes #327
> [TP-230] FCM 알림 다중 발송 테스트 api 추가

- src/main/java/com/goorm/tablepick/domain/notification/controller/NotificationController.java
- src/main/java/com/goorm/tablepick/domain/notification/dto/request/FCMLogoNotificationRequest.java
- src/main/java/com/goorm/tablepick/domain/notification/dto/response/FCMNotificationResponse.java
- src/main/java/com/goorm/tablepick/domain/notification/service/FCMService.java
- src/main/java/com/goorm/tablepick/domain/notification/service/FCMServiceImpl.java
- src/main/java/com/goorm/tablepick/domain/reservation/service/ReservationImpl.java
- #339 
- 작업 내용
- 주의사항
Closes #339
> [TP-236] 알림 부하 테스트 준비 세팅

- src/main/java/com/goorm/tablepick/domain/reservation/facade/V0/OptimisticLockFacadeV0.java
- 이슈번호 #343 
- 작업 내용
- 주의사항
Closes #12
> [TP-238] 예약 로직 수정

- src/main/java/com/goorm/tablepick/domain/reservation/facade/OptimisticLockFacade.java
- src/main/java/com/goorm/tablepick/domain/reservation/facade/V1/OptimisticLockFacadeV1.java
- src/main/java/com/goorm/tablepick/domain/reservation/facade/V2/OptimisticLockFacadeV2.java
- src/main/java/com/goorm/tablepick/global/filter/JwtTokenFilter.java
- 이슈번호 #343 
- 작업 내용
- 주의사항
Closes #12
> Tp 238 load test

- src/main/java/com/goorm/tablepick/domain/reservation/facade/V0/CreateReservationFacadeV0.java
- src/main/java/com/goorm/tablepick/domain/reservation/service/ImprovedReservationService/ReservationServiceV2.java
- 이슈번호 #364 
- 작업 내용
- 주의사항
Closes #12
> [TP-244] 결제 호출 코드 수정

- src/main/java/com/goorm/tablepick/global/config/KafkaProducerConfig.java
- 이슈번호 #364 
- 작업 내용
- 주의사항
Closes #12
> [TP-244] 카프카 설정 추가

- src/main/resources/application.yml
- 이슈번호
- 작업 내용
- 주의사항
Closes #12
> [TP-244] 카프카 설정 수정
